<a href="https://colab.research.google.com/github/Mayuri103120/DL_Learnings/blob/main/DL_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #math --> CPU
import torch #DL --> GPU 
import torchvision #datasets


In [2]:
#how numpy and pytorch work well together
a = np.random.rand(2,3)
b = torch.from_numpy(a) #call the fromnumpy func from torch to convert a numpy array to tensor

print(a)
print(b)

#datatype of elements in the torch tensor is 64-bit floting point number

[[0.25080586 0.48181043 0.52566198]
 [0.25606431 0.37945757 0.02828278]]
tensor([[0.2508, 0.4818, 0.5257],
        [0.2561, 0.3795, 0.0283]], dtype=torch.float64)


In [4]:
#we can perform efficient vectorized operations over diff dimensions of torch tensor
print(b+ 10.0)
print(torch.sin(b))
print()
print(b.sum())
print()
print(b.mean())
print()
print(b.shape)

tensor([[10.2508, 10.4818, 10.5257],
        [10.2561, 10.3795, 10.0283]], dtype=torch.float64)
tensor([[0.2482, 0.4634, 0.5018],
        [0.2533, 0.3704, 0.0283]], dtype=torch.float64)

tensor(1.9221, dtype=torch.float64)

tensor(0.3203, dtype=torch.float64)

torch.Size([2, 3])


In [5]:
#checking if gpu is available to us by calling..
torch.cuda.is_available()



True

In [6]:
#to see how much of GPU we are using is via NVIDIA..
!nvidia-smi
#so we are connected to environment that has a Tesla gpu i.e. T4 and we haven't used much of the memory yet, only 3MiB.

Thu Feb  2 06:41:19 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8    10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------